

export enum RADIX_COLORS {
    gray= "gray",
    mauve= "mauve" ,
    slate= "slate" ,
    sage= "sage" ,
    olive= "olive" ,
    sand= "sand" ,
    tomato= "tomato" ,
    red= "red" ,
    ruby= "ruby" ,
    crimson= "crimson" ,
    pink= "pink" ,
    plum= "plum" ,
    purple= "purple" ,
    violet= "violet" ,
    iris= "iris" ,
    indigo= "indigo" ,
    blue= "blue" ,
    cyan= "cyan" ,
    teal= "teal" ,
    jade= "jade" ,
    green= "green" ,
    grass= "grass" ,
    lime= "lime" ,
    yellow= "yellow" ,
    amber= "amber" ,
    orange= "orange" ,
    brown= "brown" ,
    sky= "sky" , 
};
